version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: proptrunk_db
      MYSQL_USER: pt_admin
      MYSQL_PASSWORD: pt2017
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      FLASK_CONFIG: development
      MYSQL_HOST: db
      MYSQL_DATABASE: proptrunk_db
      MYSQL_USER: pt_admin
      MYSQL_PASSWORD: pt2017
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "sleep 20 && ./venv/bin/python seed.py && ./venv/bin/gunicorn -b 0.0.0.0:8000 run:app"

volumes:
  db_data: 